src/models/Task.php
<?php

namespace models;

class Task extends \Illuminate\Database\Eloquent\Model
{
    protected $fillable = [
        'user_name','email','text', 'complected'
    ];

    public function getEditedAttribute() {
        return $this->updated_at->timestamp != $this->created_at->timestamp;
    }
}

src/models/User.php
<?php


namespace models;


use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $fillable = [
        'login','password'
    ];

}

src/controllers/AuthController.php
<?php


namespace controllers;


use kennel\session\Session;
use kennel\view\View;
use services\User\UserService;

class AuthController
{
    function index() {
        $user = !empty($_SESSION['user'])?$_SESSION['user']:false;
        return View::getInstance()->template('auth.login', [
            'message' => Session::getInstance()->getFlash(),
            'user' => $user
        ]);
    }

    function login() {
        $userService = new UserService();
        $user = $userService->login($_POST);
        if(!empty($user->id)) {
            $_SESSION['user'] = $user;
            return header('Location: /');
        }
        else {
            Session::getInstance()->addFlash(['message'=>'Введенные данные не верны!']);
        }
        return header('Location: /login');
    }

    function logout() {
        unset($_SESSION['user']);
        return header('Location: /login');
    }
}

src/controllers/TaskController.php
<?php

namespace controllers;

use kennel\Auth;
use kennel\session\Session;
use kennel\view\View;
use models\Task;
use repositories\TaskRepository;
use services\Pagination\PaginationService;
use services\Tasks\TaskService;

class TaskController
{
    public function index()
    {
        $taskRepository = new TaskRepository();
        $page = !empty($_GET['page']) ? $_GET['page'] : 1;
        $sort = !empty($_GET['sort']) ? $_GET['sort'] : false;
        $tasks = $taskRepository->paginate($page, $sort);

        return View::getInstance()->template('task.index', [
            'message' => Session::getInstance()->getFlash(),
            'sort' => $sort,
            'tasks' => $tasks,
            'user' => !empty($_SESSION['user']) ? $_SESSION['user'] : false,
            'pages' => (new PaginationService(new Task))->getPages(),
            'currentPage' => !empty($_GET['page']) ? $_GET['page'] : 1,
        ]);
    }

    public function add()
    {
        $taskService = new TaskService();
        $result = $taskService->create($_POST);

        $flash = [];
        if (!empty($result->id)) {
            $flash['message'] = 'Задача ID#'.$result->id.' успешно добавлена ';
        } elseif (is_array($result)) {
            $flash['message'] = 'Задача не прошла валидацию!';
            $flash['error'] =  $result;
        } else {
            $flash['message'] = 'Что-то пошло не так!';
        }

        Session::getInstance()->addFlash($flash);

        return header('Location: /');
    }

    public function update()
    {
        if (!Auth::admin()) {
            Session::getInstance()->addFlash(['message' => 'Редактирование доступно только администратору!']);
            return header('Location: /login');

            return false;
        }

        $result = (new TaskService())->update($_POST);
        $flash = [];
        if ($result !== false) {
           $flash['message'] = 'Задача успешно обновлена';
        } elseif (is_array($result)) {
            $flash['message'] = 'Задача не прошла валидацию!';
            $flash['error'] = $result;
        } else {
            $flash['message'] = 'Что-то пошло не так!';
        }
        Session::getInstance()->addFlash($flash);

        return header('Location: /');
    }

}

src/views/layout/task.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Task</title>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="/css/style.css" rel="stylesheet"/>
    <script type="text/javascript" src="/js/task.js"></script>
</head>
<body>
<div class="topmenu">
    <a href="/">Задачи</a>
    @if(\kennel\Auth::admin())
        <a href="/logout">Выйти</a>
    @else
        <a href="/login">Войти</a>
    @endif
</div>
@yield('content')

</body>
</html>

src/views/messages/messages.blade.php
@if($message)
    <div class="alert alert-primary" role="alert">{{$message['message']}}</div>
@endif
@isset($message['error'])
    @foreach($message['error'] as $field=>$value)
        <div class="alert alert-danger" role="alert">
            Поле  {{$field}}  имеет недопустимое значение
        </div>
    @endforeach
@endisset

src/views/task/admin/form_update.blade.php
<form action="/task/update" method="POST" class="taskform">
    <div class="mb-3">
        <label class="form-label">Текст задачи</label>
        <textarea name="text" class="form-control">{{$task->text}}</textarea>
    </div>
    <div class="form-check">
        <label>
            <input class="form-check-input"
                   type="checkbox"
                   name="complected"
                   @if($task->complected) checked="checked" @endif
            /> Выполнена
        </label>
    </div>
    <input type="hidden" name="task_id" value="{{$task->id}}"/>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>

src/views/task/form.blade.php
<form action="/task/add" method="POST" class="taskform">
    <div class="mb-3">
        <label class="form-label">Имя пользователя </label>
        <input type="text" name="user_name" required class="form-control"/>
    </div>
    <div class="mb-3">
        <label class="form-label">E-mail</label>
        <input type="email" name="email" required class="form-control"/>
    </div>
    <div class="mb-3">
        <label class="form-label">Текст задачи</label>
        <textarea name="text" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>

src/views/task/index.blade.php
@extends('layout.task')

@section('content')
    <div class="container">
        @include('messages.messages')
        @include('task.sorting')
        @include('task.list')
        @include('task.pagination')
        @include('task.form')
    </div>
@endsection

src/views/task/list.blade.php
@foreach($tasks as $task)
    <div class="task" id="task_{{$task->id}}">
        @if($task->edited)
            Отредактированно Администратором
        @endif
        <div>
            Текст: {!! $task->text !!}
        </div>
        <div>
            Email: {{$task->email}}
        </div>
        <div>
            Имя пользователя: {{$task->user_name}}
        </div>
        <div>
            Статус:
            @if($task->complected)
                Выполнена
            @else
                Не выполнена
            @endif
        </div>
        @if($user)
            <div class="updateForm">
                @include('task.admin.form_update')
            </div>
            <button class="btn btn-success" onclick="editTask({{$task->id}})">Редактировать</button>
        @endif
    </div>
@endforeach

src/views/task/pagination.blade.php
@if(count($pages) > 7)
    <div class="pagination">
        <span>Страницы:</span>
        @foreach($pages as $page)
            @php
                $class = ($page == $currentPage)?'class=active':'';
            @endphp
            @if($sort)
                <a {{$class}} href="?page={{$page}}&sort={{$sort}}">{{$page}}</a>
            @else
                <a {{$class}} href="?page={{$page}}">{{$page}}</a>
            @endif
        @endforeach
    </div>
@endif

src/views/task/sorting.blade.php
<div class="sort">
    Сортировать:
    <a href="/?page={{$currentPage}}&sort=user_name">По имени пользователя</a>
    <a href="/?page={{$currentPage}}&sort=email">По email</a>
    <a href="/?page={{$currentPage}}&sort=complected">По статусу</a>
</div>